config/routes.rb
Rails.application.routes.draw do

  resources :activities do
    resources :comments
    resources :rsvps
  end
  
  resources :events do
    resources :comments
    resources :rsvps
  end

  root 'pages#home'

  get 'pages/home'

  get 'pages/accommodations'

  get 'pages/contact'

  get 'agenda' => 'pages#agenda'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :comments, as: :commentable
  has_many :rsvps, as: :rsvpable
  belongs_to :state

  #STATES = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming' ]

  #validates :state, inclusion: { in: STATES }

  
end #Activity

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
    @commentable = @activity
    @comments = @commentable.comments
    @comment = Comment.new

    @rsvpable = @activity
    @rsvps = @rsvpable.rsvps
    @rsvp = Rsvp.new
  end #show

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :venue, :street_address, :city, :state_id, :zip, :website, :description)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.collection_select :state_id, State.order(:name), :id, :name, prompt: "Choose a State"  %>

  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '+ New Activity', new_activity_path %>
<h1>Area Activities </h1>
<p>Interesting things to do while you're in the area</p>

<% @activities.order("name ASC").each do |activity| %>
  <article class="col-sm-3 index-listing">
    <div class="index-buttons">
      <%= link_to 'Edit', edit_activity_path(activity) %> |
      <%= link_to 'Delete', activity, method: :delete, data: { confirm: 'Are you sure you want to delete #{activity.name}? This action cannot be undone.' } %>
    </div> <!-- index-buttons -->
    <h2><%= link_to activity.name, activity %></h2>
    <p><%= truncate(activity.description, length: 65, separator: " ") %> <%= link_to "read more", activity, class: "read-more" %></p> 
  </article> <!-- index-listing -->
<% end %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>
  
<div class="col-xs-9">
  <h2><%= @activity.name %> <span class="edit-link"><%= link_to '(Edit)', edit_activity_path(@activity) %> </span></h2>
  <div class="row">
    <div class="col-xs-6">
      <h4>Location</h4>
      <p>
        <%= @activity.venue %> <br>
        <%= @activity.street_address %> <br>
        <%= @activity.city %>, <%= @activity.state.abbreviation %> <%= @activity.zip %> <br>
        <%= link_to @activity.website, @activity.website, :target => "_blank" %>
      </p>
    </div> <!-- col-xs-6 -->

    <div class="col-xs-6">
      <h4>Description</h4>
      <p><%= @activity.description %></p>
    </div> <!-- col-xs-6 -->
  </div> <!-- row -->
  
  <div class="row">  
    <hr>
    <h3>Comments</h3>
    <%= render "comments/comment" %>
    <hr>

    <h3>Leave a Comment</h3>
    <%= render "comments/form" %>
    <hr>

  </div> <!-- col-xs-9 -->
</div> <!-- row -->

<div class="col-xs-3">
  <%= render "layouts/sidebar" %> 
</div> <!-- col-xs-3 -->