config/routes.rb
Rails.application.routes.draw do

  resources :activities do
    resources :comments
    resources :rsvps
  end
  
  resources :events do
    resources :comments
    resources :rsvps
  end

  root 'pages#home'

  get 'pages/home'

  get 'pages/accommodations'

  get 'pages/contact'

  get 'agenda' => 'pages#agenda'

end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ReUnion</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="/agenda" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Agenda <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Events", events_path %></li>
              <li><%= link_to "Activities", activities_path %></li>
            </ul>
          </li><!-- dropdown -->
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Activities", activities_path %></li>
          <li><%= link_to "Accommodations", pages_accommodations_path %></li>
          <li><%= link_to "Contact", pages_contact_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <h3><%= pluralize(@rsvpable.rsvps.count, "Person") %> Attending</h3>
  <%= render "rsvps/rsvp" %>
  <hr>

  <h3>Sign Up for <%= @rsvpable.name %></h3>
  <%= render "rsvps/form" %>
  <hr>
</div> <!-- sidebar -->
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reunion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  
</head>
<body>
  <div class="container">
  <%= render "layouts/header" %>
  
  <%= yield %>
     
  </div> <!-- container -->
    
</body>
</html>